language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add build
  - git commit -m 'Automatic build [skip travis]'
  - git remote add origin "https://${GH_TOKEN}@github.com/grapenut/mush-portal.git"
  - git remote -v
  - git push origin master

