language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add build
  - git commit -m "Travis build: $TRAVIS_BUILD_NUMBER [skip travis]
  - git remote add secret https://${SECRET_KEY}@github.com/grapenut/mush-portal.git > /dev/null 2>&1
  - git push --set-upstream secret master

